    #######
# Cloudify Blueprint which runs a bash script

imports:
    - cloudify.types
    - openstack_host_provisioner

# The blueprint contains two nodes, a vm and a web server hosted in it.
blueprint:
    name: bash_runner_v11
    topology:
        -   name: vm
            type: openstack_host

        -   name: bash_runner
            type: bash_runner
            properties:
                port: 8080
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: vm

#######
# Types and implementation details.
#
plugins:
    bash_runner:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            url: https://github.com/rantav/cosmo-plugin-bash-runner/archive/tty.js.zip

types:
    openstack_host:
        derived_from: cloudify.types.host
        properties:
            -   install_agent: true
            -   worker_config:
                    user: ubuntu
                    port: 22
                    key: ~/.ssh/cloudify-agents-kp.pem
            -   nova_config:
                    region: az-2.region-a.geo-1
                    instance:
                        name: bash_runner
                        image: 67074
                        flavor: 101
                        key_name: cloudify-agents-kp-rantav2
        interfaces:
            cloudify.interfaces.lifecycle:
                -   create: openstack_host_provisioner.tasks.provision
                -   start: openstack_host_provisioner.tasks.start
    bash_runner:
        derived_from: cloudify.types.web_server
        interfaces:
            cloudify.interfaces.lifecycle:
                -   start: bash_runner.tasks.start
